#ifndef CONFIG_H
#define CONFIG_H

//#define HEARTBEAT_LOG
#define MSGCLIENT_LOG

#define BROADCAST_PERIOD 1
#define HEARTBEAT_SEND_PORT 7777
#define HEARTBEAT_RECV_PORT 7778
#define MSG_SERVER_PORT 8888

#define MAX_UDP_BUF_SIZE 1024
#define MAX_TCP_BUF_SIZE 1024

#define PRIVATEKEY_PATH "./private.key"

#define BUFF_SIZE 1024
#define MAX_BUF_LEN 1024
#define MAX_SEND_LEN 1024

#endif // CONFIG_H
